### ISSUE TITLE
Open related notification when pressing enter

### ISSUE THREAD

**Issue by FelipePhilippCbh** [Garulf/Github-Notifications#58]
Not sure if it is a bug or is missing a feature, but when I open the notifications list and press enter in any of the notifications, the launcher closes. Is this expected?

**Comment by FelipePhilippCbh** [comment]
It works now, probably an issue on my end

**Comment by Garulf** [comment]
Oh that's strange, it uses Python's standard library `webbrowser.open` function using the URL GitHub provides from the API. 

It should be as basic as it gets. 

Either way glad it's working for you.
